### ISSUE TITLE
Right-clicking wool sleeping bags does damage

### ISSUE THREAD

**Issue by ghost** [NathanSalapat/survival#2]
When attempting to sleep in a wool sleeping bag, the player receives damage.  This happens during the day - with the message that you can only sleep at night - and also at night prior to laying down.

**Comment by NathanSalapat** [comment]
I know about this error, I have to create the sleep functions for the sleeping bags and leafy beds myself, as right now they just use the beds function. Comment out lines 198 and 199 in the nodes.lua file to remove. It should be fixed in a few releases.

**Comment by NathanSalapat** [comment]
Latest update removes this.
