### ISSUE TITLE
Spigot accepts multiple buckets, returns only one.

### ISSUE THREAD

**Issue by ghost** [NathanSalapat/survival#3]
When placing multiple empty buckets on a spigot, only one bucket of sap is returned, thus loosing however many empty buckets.

**Comment by NathanSalapat** [comment]
Well then I guess this bit of code [inv:set_size('sap', 1)] doesn't do what I expected. I thought it would only allow one item to be placed. I'll have to look into how to limit that. The spigot is only suppose to let you place one bucket at a time, I didn't want to make gathering sap too easy. Though I did notice you can place four spigots on a single tree trunk node.

**Comment by NathanSalapat** [comment]
Fixed, I checked how the bees mod was accomplishing this for the bee hives and found the solution.
